site_name: Alan's Notes
site_url: https://alanshin.github.io/notes/
repo_url: https://github.com/alanshin/notes

theme:
  name: material

  palette:
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

nav:
- Home: 'index.md'